// packages/react/src/card/Card.tsx
import type { ReactNode } from "react";

export interface CardProps {
  title?: ReactNode;
  extra?: ReactNode;
  footer?: ReactNode;
  noBody?: boolean;
  children?: ReactNode;
}

export function Card({ title, extra, footer, noBody = false, children }: CardProps) {
  return (
    <div className="ag-card">
      {title || extra ? (
        <div className="ag-card__header">
          <h3 className="ag-card__title">{title}</h3>
          {extra ? <div className="ag-card__extra">{extra}</div> : null}
        </div>
      ) : null}
      {noBody ? children : <div className="ag-card__body">{children}</div>}
      {footer ? <div className="ag-card__footer">{footer}</div> : null}
    </div>
  );
}

// packages/vue/src/card/Card.vue
<script setup lang="ts">
import { useSlots } from "vue";

withDefaults(
  defineProps<{
    title?: string;
    noBody?: boolean;
  }>(),
  { noBody: false },
);

const slots = useSlots();
</script>

<template>
  <div class="ag-card">
    <div v-if="title || slots.extra || $slots.extra" class="ag-card__header">
      <h3 class="ag-card__title">{{ title }}</h3>
      <div v-if="slots.extra || $slots.extra" class="ag-card__extra">
        <slot name="extra" />
      </div>
    </div>
    <div v-if="!noBody" class="ag-card__body">
      <slot />
    </div>
    <slot v-else />
    <div v-if="slots.footer || $slots.footer" class="ag-card__footer">
      <slot name="footer" />
    </div>
  </div>
</template>
