// packages/vue/src/spin/Spin.vue
<script setup lang="ts">
import { useSlots } from "vue";

export type SpinSize = "sm" | "md" | "lg";

withDefaults(
  defineProps<{
    spinning?: boolean;
    size?: SpinSize;
    text?: string;
  }>(),
  { spinning: true, size: "md", text: "" },
);

const slots = useSlots();
</script>

<template>
  <div
    v-if="slots.default || $slots.default"
    class="ag-spin ag-spin--wrap"
    :class="size !== 'md' ? `ag-spin--${size}` : ''"
  >
    <slot />
    <div v-if="spinning" class="ag-spin__mask">
      <span class="ag-spin__spinner" />
      <span v-if="text" class="ag-spin__text">{{ text }}</span>
    </div>
  </div>
  <div
    v-else
    class="ag-spin"
    :class="[size !== 'md' ? `ag-spin--${size}` : '', text ? 'ag-spin--with-text' : '']"
  >
    <span class="ag-spin__spinner" />
    <span v-if="text" class="ag-spin__text">{{ text }}</span>
  </div>
</template>

// packages/react/src/spin/Spin.tsx
import type { ReactNode } from "react";

export type SpinSize = "sm" | "md" | "lg";

export interface SpinProps {
  spinning?: boolean;
  size?: SpinSize;
  text?: string;
  children?: ReactNode;
}

export function Spin({ spinning = true, size = "md", text, children }: SpinProps) {
  const sizeClass = size !== "md" ? ` ag-spin--${size}` : "";

  if (children) {
    return (
      <div className={`ag-spin ag-spin--wrap${sizeClass}`}>
        {children}
        {spinning ? (
          <div className="ag-spin__mask">
            <span className="ag-spin__spinner" />
            {text ? <span className="ag-spin__text">{text}</span> : null}
          </div>
        ) : null}
      </div>
    );
  }

  return (
    <div className={`ag-spin${sizeClass}`}>
      <span className="ag-spin__spinner" />
      {text ? <span className="ag-spin__text">{text}</span> : null}
    </div>
  );
}
