// packages/vue/src/pro/CrudFormModal.vue
<script setup lang="ts">
import { computed, reactive, ref, watch } from "vue";
import type { CrudField } from "@argon-kit/core";
import { message } from "@argon-kit/core";
import Modal from "../overlay/Modal.vue";
import Form from "../form/Form.vue";
import FormItem from "../form/FormItem.vue";
import Input from "../input/Input.vue";
import Password from "../input/Password.vue";
import Textarea from "../input/Textarea.vue";
import InputNumber from "../input/InputNumber.vue";
import Select from "../select/Select.vue";
import Switch from "../switch/Switch.vue";
import DatePicker from "../datepicker/DatePicker.vue";
import RangePicker from "../datepicker/RangePicker.vue";
import TreeSelect from "../tree/TreeSelect.vue";

const props = withDefaults(
  defineProps<{
    open: boolean;
    /** null=新增，否则编辑 */
    recordId: string | number | null;
    fields: CrudField[];
    title: string;
    /** 编辑态回填 */
    onLoad?: (id: string | number) => Promise<Record<string, unknown>>;
    onSubmit: (values: Record<string, unknown>, isEdit: boolean) => Promise<void>;
    onSuccess?: () => void;
    onCancel: () => void;
    width?: number;
  }>(),
  { width: 600 },
);

const isEdit = computed(() => props.recordId != null);
const modalTitle = computed(() => (isEdit.value ? `编辑${props.title}` : `新增${props.title}`));

const model = reactive<Record<string, unknown>>({});
const formRef = ref<InstanceType<typeof Form> | null>(null);
const submitting = ref(false);
const loadingRecord = ref(false);

function resetModel() {
  Object.keys(model).forEach((k) => delete model[k]);
  for (const f of props.fields) {
    model[f.name] = f.type === "switch" ? false : f.type === "dateRange" ? null : "";
  }
}

// open / recordId 变化 → 回填或重置
watch(
  () => [props.open, props.recordId] as const,
  async ([open]) => {
    if (!open) return;
    resetModel();
    if (isEdit.value && props.onLoad) {
      loadingRecord.value = true;
      try {
        const record = await props.onLoad(props.recordId as string | number);
        for (const f of props.fields) {
          const v = record[f.name];
          if (v === undefined) continue;
          model[f.name] = f.type === "switch" ? v === 1 || v === true : v;
        }
      } finally {
        loadingRecord.value = false;
      }
    }
    formRef.value?.clearValidate();
  },
  { immediate: true },
);

async function handleConfirm() {
  if (!formRef.value || submitting.value) return;
  let values: Record<string, unknown>;
  try {
    values = await formRef.value.validate();
  } catch {
    return; // 校验失败已标红
  }
  // switch boolean → 1/0（对齐后端惯例）
  for (const f of props.fields) {
    if (f.type === "switch") values[f.name] = values[f.name] ? 1 : 0;
  }
  submitting.value = true;
  try {
    await props.onSubmit(values, isEdit.value);
    message.success(isEdit.value ? "编辑成功" : "新增成功");
    props.onSuccess?.();
  } finally {
    submitting.value = false;
  }
}
</script>

<template>
  <Modal
    :open="open"
    :title="modalTitle"
    :width="width"
    :confirm-loading="submitting"
    @close="onCancel"
    @confirm="handleConfirm"
  >
    <div v-if="loadingRecord" style="padding: 40px; text-align: center; color: var(--ag-gray-500)">
      加载中…
    </div>
    <Form v-else ref="formRef" :model="model">
      <FormItem
        v-for="f in fields"
        :key="f.name"
        :label="f.label"
        :name="f.name"
        :rules="f.rules"
        :span="f.span"
      >
        <template v-if="f.type === 'render'">
          <slot :name="`field-${f.name}`" :model="model" :field="f" />
        </template>
        <Input
          v-else-if="f.type === 'password'"
          :placeholder="f.placeholder"
          @update:model-value="(v: string) => (model[f.name] = v)"
          :model-value="String(model[f.name] ?? '')"
        />
        <Textarea
          v-else-if="f.type === 'textarea'"
          :rows="2"
          :placeholder="f.placeholder"
          :model-value="String(model[f.name] ?? '')"
          @update:model-value="(v: string) => (model[f.name] = v)"
        />
        <InputNumber
          v-else-if="f.type === 'number'"
          :placeholder="f.placeholder"
          :model-value="String(model[f.name] ?? '')"
          @update:model-value="(v: string) => (model[f.name] = v)"
        />
        <Select
          v-else-if="f.type === 'select'"
          :options="f.options ?? []"
          :placeholder="f.placeholder"
          :model-value="(model[f.name] as string | number | null)"
          @update:model-value="(v) => (model[f.name] = v)"
        />
        <Switch
          v-else-if="f.type === 'switch'"
          :model-value="Boolean(model[f.name])"
          @update:model-value="(v: boolean) => (model[f.name] = v)"
        />
        <DatePicker
          v-else-if="f.type === 'date'"
          :placeholder="f.placeholder"
          :model-value="(model[f.name] as string | null)"
          @update:model-value="(v) => (model[f.name] = v)"
        />
        <RangePicker
          v-else-if="f.type === 'dateRange'"
          :model-value="(model[f.name] as [string, string] | null)"
          @update:model-value="(v) => (model[f.name] = v)"
        />
        <TreeSelect
          v-else-if="f.type === 'treeSelect'"
          :data="f.data ?? []"
          :placeholder="f.placeholder"
          :model-value="(model[f.name] as string | number | null)"
          @update:model-value="(v) => (model[f.name] = v)"
        />
        <Input
          v-else
          :placeholder="f.placeholder"
          :model-value="String(model[f.name] ?? '')"
          @update:model-value="(v: string) => (model[f.name] = v)"
        />
      </FormItem>
    </Form>
  </Modal>
</template>

// packages/react/src/pro/CrudFormModal.tsx
import { useEffect, useMemo, useState, type ReactNode } from "react";
import type { CrudField } from "@argon-kit/core";
import { message } from "@argon-kit/core";
import { Modal } from "../overlay/Modal";
import { Form, FormItem } from "../form/Form";
import { Input } from "../input/Input";
import { Password } from "../input/Password";
import { Textarea } from "../input/Textarea";
import { InputNumber } from "../input/InputNumber";
import { Select } from "../select/Select";
import { Switch } from "../switch/Switch";
import { DatePicker, RangePicker } from "../datepicker/DatePicker";
import { TreeSelect } from "../tree/TreeSelect";

export interface CrudFormModalProps {
  open: boolean;
  recordId: string | number | null;
  fields: CrudField[];
  title: string;
  onLoad?: (id: string | number) => Promise<Record<string, unknown>>;
  onSubmit: (values: Record<string, unknown>, isEdit: boolean) => Promise<void>;
  onSuccess?: () => void;
  onCancel: () => void;
  width?: number;
  /** render 逃逸字段 */
  renderField?: (field: CrudField, model: Record<string, unknown>) => ReactNode;
}

export function CrudFormModal({
  open,
  recordId,
  fields,
  title,
  onLoad,
  onSubmit,
  onSuccess,
  onCancel,
  width = 600,
  renderField,
}: CrudFormModalProps) {
  const isEdit = recordId != null;
  const [model, setModel] = useState<Record<string, unknown>>({});
  const [errors, setErrors] = useState<Record<string, string>>({});
  const [submitting, setSubmitting] = useState(false);
  const [loadingRecord, setLoadingRecord] = useState(false);

  const emptyModel = useMemo(() => {
    const m: Record<string, unknown> = {};
    for (const f of fields) m[f.name] = f.type === "switch" ? false : f.type === "dateRange" ? null : "";
    return m;
  }, [fields]);

  useEffect(() => {
    if (!open) return;
    let alive = true;
    setErrors({});
    if (isEdit && onLoad) {
      setLoadingRecord(true);
      onLoad(recordId)
        .then((record) => {
          if (!alive) return;
          const next = { ...emptyModel };
          for (const f of fields) {
            const v = record[f.name];
            if (v !== undefined) next[f.name] = f.type === "switch" ? v === 1 || v === true : v;
          }
          setModel(next);
        })
        .finally(() => alive && setLoadingRecord(false));
    } else {
      setModel(emptyModel);
    }
    return () => {
      alive = false;
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [open, recordId]);

  const setField = (name: string, v: unknown) => setModel((m) => ({ ...m, [name]: v }));

  async function handleConfirm() {
    if (submitting) return;
    // 本地校验（字段级规则聚合）
    const errs: Record<string, string> = {};
    await Promise.all(
      fields.map(async (f) => {
        if (!f.rules?.length) return;
        const { validateField } = await import("@argon-kit/core");
        const msg = await validateField(model[f.name], f.rules);
        if (msg) errs[f.name] = msg;
      }),
    );
    if (Object.keys(errs).length) {
      setErrors(errs);
      return;
    }
    const values: Record<string, unknown> = { ...model };
    for (const f of fields) {
      if (f.type === "switch") values[f.name] = values[f.name] ? 1 : 0;
    }
    setSubmitting(true);
    try {
      await onSubmit(values, isEdit);
      message.success(isEdit ? "编辑成功" : "新增成功");
      onSuccess?.();
    } finally {
      setSubmitting(false);
    }
  }

  return (
    <Modal
      open={open}
      title={isEdit ? `编辑${title}` : `新增${title}`}
      width={width}
      confirmLoading={submitting}
      onClose={onCancel}
      onConfirm={handleConfirm}
    >
      {loadingRecord ? (
        <div style={{ padding: 40, textAlign: "center", color: "var(--ag-gray-500)" }}>加载中…</div>
      ) : (
        <Form model={model} layout="vertical">
          {fields.map((f) => {
            const err = errors[f.name];
            const control =
              f.type === "render" ? (
                renderField?.(f, model)
              ) : f.type === "password" ? (
                <Password
                  placeholder={f.placeholder}
                  value={String(model[f.name] ?? "")}
                  onChange={(e) => setField(f.name, e.target.value)}
                  status={err ? "error" : undefined}
                />
              ) : f.type === "textarea" ? (
                <Textarea
                  rows={2}
                  placeholder={f.placeholder}
                  value={String(model[f.name] ?? "")}
                  onChange={(e) => setField(f.name, e.target.value)}
                  status={err ? "error" : undefined}
                />
              ) : f.type === "number" ? (
                <InputNumber
                  placeholder={f.placeholder}
                  value={String(model[f.name] ?? "")}
                  onChange={(e) => setField(f.name, e.target.value)}
                  status={err ? "error" : undefined}
                />
              ) : f.type === "select" ? (
                <Select
                  options={f.options ?? []}
                  placeholder={f.placeholder}
                  value={(model[f.name] as string | number | null) ?? null}
                  onChange={(v) => setField(f.name, v)}
                  status={err ? "error" : undefined}
                />
              ) : f.type === "switch" ? (
                <Switch
                  checked={Boolean(model[f.name])}
                  onChange={(v) => setField(f.name, v)}
                />
              ) : f.type === "date" ? (
                <DatePicker
                  placeholder={f.placeholder}
                  value={(model[f.name] as string | null) ?? null}
                  onChange={(v) => setField(f.name, v)}
                  status={err ? "error" : undefined}
                />
              ) : f.type === "dateRange" ? (
                <RangePicker
                  value={(model[f.name] as [string, string] | null) ?? null}
                  onChange={(v) => setField(f.name, v)}
                  status={err ? "error" : undefined}
                />
              ) : f.type === "treeSelect" ? (
                <TreeSelect
                  data={f.data ?? []}
                  placeholder={f.placeholder}
                  value={(model[f.name] as string | number | null) ?? null}
                  onChange={(v) => setField(f.name, v)}
                  status={err ? "error" : undefined}
                />
              ) : (
                <Input
                  placeholder={f.placeholder}
                  value={String(model[f.name] ?? "")}
                  onChange={(e) => setField(f.name, e.target.value)}
                  status={err ? "error" : undefined}
                />
              );
            return (
              <FormItem key={f.name} label={f.label} name={f.name} span={f.span}>
                {control}
                {err ? <span className="ag-form-item__error">{err}</span> : null}
              </FormItem>
            );
          })}
        </Form>
      )}
    </Modal>
  );
}
