// packages/charts/src/react/Chart.tsx
import { useEffect, useRef } from "react";
import {
  Chart,
  registerables,
  type ChartConfiguration,
  type ChartType,
} from "chart.js";
import {
  applyChartDefaults,
  baseOptionsFor,
  withPalette,
  type ChartKind,
} from "../core/chartTheme";

Chart.register(...registerables);
applyChartDefaults(Chart);

export type { ChartKind };

export interface ArgonChartProps {
  kind?: ChartKind;
  labels: string[];
  datasets: Array<Record<string, unknown>>;
  options?: Record<string, unknown>;
  height?: number;
}

export function ArgonChart({
  kind = "line",
  labels,
  datasets,
  options,
  height = 300,
}: ArgonChartProps) {
  const canvasRef = useRef<HTMLCanvasElement | null>(null);
  const chartRef = useRef<Chart | null>(null);

  // kind 变化 → 重建
  useEffect(() => {
    if (!canvasRef.current) return;
    const config: ChartConfiguration = {
      type: kind as ChartType,
      data: {
        labels,
        datasets: withPalette(datasets as Array<{ backgroundColor?: unknown }>) as never,
      },
      options: { ...baseOptionsFor(kind), ...options },
    };
    chartRef.current = new Chart(canvasRef.current, config);
    return () => {
      chartRef.current?.destroy();
      chartRef.current = null;
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [kind]);

  // 数据/options 变化 → 原地更新
  useEffect(() => {
    const chart = chartRef.current;
    if (!chart) return;
    chart.data.labels = labels;
    chart.data.datasets = withPalette(
      datasets as Array<{ backgroundColor?: unknown }>,
    ) as never;
    chart.options = { ...baseOptionsFor(kind), ...options };
    chart.update();
  }, [kind, labels, datasets, options]);

  return (
    <div className="ag-chart" style={{ height }}>
      <canvas ref={canvasRef} />
    </div>
  );
}

export const LineChart = (p: Omit<ArgonChartProps, "kind">) => <ArgonChart {...p} kind="line" />;
export const BarChart = (p: Omit<ArgonChartProps, "kind">) => <ArgonChart {...p} kind="bar" />;
export const PieChart = (p: Omit<ArgonChartProps, "kind">) => <ArgonChart {...p} kind="pie" />;
export const DoughnutChart = (p: Omit<ArgonChartProps, "kind">) => <ArgonChart {...p} kind="doughnut" />;

// packages/charts/src/svelte/Chart.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import { Chart, registerables, type ChartConfiguration, type ChartType } from "chart.js";
  import {
    applyChartDefaults,
    baseOptionsFor,
    withPalette,
    type ChartKind,
  } from "../core/chartTheme";

  Chart.register(...registerables);
  applyChartDefaults(Chart);

  let {
    kind = "line",
    labels,
    datasets,
    options = {},
    height = 300,
  }: {
    kind?: ChartKind;
    labels: string[];
    datasets: Array<Record<string, unknown>>;
    options?: Record<string, unknown>;
    height?: number;
  } = $props();

  let canvas: HTMLCanvasElement;
  let chart: Chart | null = null;
  let currentKind: ChartKind = kind;

  function buildConfig(): ChartConfiguration {
    return {
      type: kind as ChartType,
      data: {
        labels,
        datasets: withPalette(datasets as Array<{ backgroundColor?: unknown }>) as never,
      },
      options: { ...baseOptionsFor(kind), ...options },
    };
  }

  onMount(() => {
    currentKind = kind;
    chart = canvas ? new Chart(canvas, buildConfig()) : null;
    return () => chart?.destroy();
  });

  // kind 变化 → 重建
  $effect(() => {
    if (kind === currentKind) return;
    currentKind = kind;
    chart?.destroy();
    chart = canvas ? new Chart(canvas, buildConfig()) : null;
  });

  // 数据/options 变化 → 原地更新
  $effect(() => {
    void labels;
    void datasets;
    void options;
    if (!chart || kind !== currentKind) return;
    chart.data.labels = labels;
    chart.data.datasets = withPalette(datasets as Array<{ backgroundColor?: unknown }>) as never;
    chart.options = { ...baseOptionsFor(kind), ...options };
    chart.update();
  });
</script>

<div class="ag-chart" style="height:{height}px">
  <!-- svelte-ignore a11y_no_noninteractive_element_interactions -->
  <canvas bind:this={canvas}></canvas>
</div>
