// packages/plugins/src/tags/vue/TagsInput.vue
<script setup lang="ts">
import { computed, ref } from "vue";
import type { TagsInputProps } from "../../core/types";

const props = withDefaults(defineProps<TagsInputProps>(), {
  value: () => [],
  placeholder: "输入后回车添加",
  maxTags: Infinity,
  onlyUnique: false,
  disabled: false,
});

const emit = defineEmits<{ "update:modelValue": [string[]] }>();

const input = ref("");

const canAdd = computed(
  () =>
    !props.disabled &&
    input.value.trim().length > 0 &&
    props.value.length < props.maxTags &&
    (!props.onlyUnique || !props.value.includes(input.value.trim())),
);

function add() {
  if (!canAdd.value) {
    input.value = "";
    return;
  }
  const next = [...props.value, input.value.trim()];
  emit("update:modelValue", next);
  props.onChange?.(next);
  input.value = "";
}

function remove(tag: string) {
  if (props.disabled) return;
  const next = props.value.filter((t) => t !== tag);
  emit("update:modelValue", next);
  props.onChange?.(next);
}

function onKeydown(e: KeyboardEvent) {
  if (e.key === "Enter") {
    e.preventDefault();
    add();
  } else if (e.key === "Backspace" && input.value === "" && props.value.length) {
    remove(props.value[props.value.length - 1]);
  }
}
</script>

<template>
  <div class="ag-tags" :class="{ 'is-disabled': disabled }">
    <span v-for="tag in value" :key="tag" class="ag-tags__tag">
      {{ tag }}
      <button
        v-if="!disabled"
        type="button"
        class="ag-tags__remove"
        aria-label="remove"
        @click="remove(tag)"
      >×</button>
    </span>
    <input
      v-model="input"
      class="ag-tags__input"
      :placeholder="value.length ? '' : placeholder"
      :disabled="disabled"
      @keydown="onKeydown"
      @blur="add"
    />
  </div>
</template>

// packages/plugins/src/tags/react/TagsInput.tsx
import { useState } from "react";
import type { TagsInputProps } from "../../core/types";

export function TagsInput({
  value = [],
  placeholder = "输入后回车添加",
  maxTags = Infinity,
  onlyUnique = false,
  disabled = false,
  onChange,
}: TagsInputProps) {
  const [input, setInput] = useState("");

  const canAdd =
    !disabled &&
    input.trim().length > 0 &&
    value.length < maxTags &&
    (!onlyUnique || !value.includes(input.trim()));

  const commit = () => {
    if (!canAdd) {
      setInput("");
      return;
    }
    const next = [...value, input.trim()];
    onChange?.(next);
    setInput("");
  };

  const remove = (tag: string) => {
    if (disabled) return;
    onChange?.(value.filter((t) => t !== tag));
  };

  const onKeydown = (e: React.KeyboardEvent) => {
    if (e.key === "Enter") {
      e.preventDefault();
      commit();
    } else if (e.key === "Backspace" && input === "" && value.length) {
      remove(value[value.length - 1]);
    }
  };

  return (
    <div className={disabled ? "ag-tags is-disabled" : "ag-tags"}>
      {value.map((tag) => (
        <span key={tag} className="ag-tags__tag">
          {tag}
          {!disabled ? (
            <button
              type="button"
              className="ag-tags__remove"
              aria-label="remove"
              onClick={() => remove(tag)}
            >
              ×
            </button>
          ) : null}
        </span>
      ))}
      <input
        className="ag-tags__input"
        placeholder={value.length ? "" : placeholder}
        disabled={disabled}
        value={input}
        onChange={(e) => setInput(e.target.value)}
        onKeyDown={onKeydown}
        onBlur={commit}
      />
    </div>
  );
}
