// packages/react/src/layout/Transfer.tsx
import { useState } from "react";
import type { TransferItem } from "@argon-kit/core";
import { Button } from "../button/Button";
import { Checkbox } from "../checkbox/Checkbox";

export function Transfer({
  data,
  value = [],
  onChange,
  titles = ["待选", "已选"],
}: {
  data: TransferItem[];
  value?: string[];
  onChange?: (keys: string[]) => void;
  titles?: [string, string];
}) {
  const [leftChecked, setLeftChecked] = useState<string[]>([]);
  const [rightChecked, setRightChecked] = useState<string[]>([]);
  const selected = new Set(value);
  const left = data.filter((d) => !selected.has(d.key));
  const right = data.filter((d) => selected.has(d.key));

  function toggle(list: string[], set: (v: string[]) => void, key: string, on: boolean) {
    set(on ? [...list, key] : list.filter((k) => k !== key));
  }

  function moveRight() {
    onChange?.([...value, ...leftChecked]);
    setLeftChecked([]);
  }

  function moveLeft() {
    const drop = new Set(rightChecked);
    onChange?.(value.filter((k) => !drop.has(k)));
    setRightChecked([]);
  }

  function panel(
    title: string,
    items: TransferItem[],
    checked: string[],
    setChecked: (v: string[]) => void,
  ) {
    return (
      <div className="ag-transfer__panel">
        <div className="ag-transfer__head">
          {title}（{items.length}）
        </div>
        <ul className="ag-transfer__list">
          {items.map((it) => (
            <li key={it.key}>
              <Checkbox
                checked={checked.includes(it.key)}
                disabled={it.disabled}
                onChange={(on) => toggle(checked, setChecked, it.key, on)}
              >
                {it.label}
              </Checkbox>
            </li>
          ))}
        </ul>
      </div>
    );
  }

  return (
    <div className="ag-transfer">
      {panel(titles[0], left, leftChecked, setLeftChecked)}
      <div className="ag-transfer__ops">
        <Button size="sm" disabled={!leftChecked.length} onClick={moveRight} aria-label="移到右侧">
          ›
        </Button>
        <Button size="sm" variant="neutral" disabled={!rightChecked.length} onClick={moveLeft} aria-label="移到左侧">
          ‹
        </Button>
      </div>
      {panel(titles[1], right, rightChecked, setRightChecked)}
    </div>
  );
}

// packages/vue/src/layout/Transfer.vue
<script setup lang="ts">
import { computed, ref } from "vue";
import type { TransferItem } from "@argon-kit/core";
import Button from "../button/Button.vue";
import Checkbox from "../checkbox/Checkbox.vue";

const props = withDefaults(
  defineProps<{
    data: TransferItem[];
    titles?: [string, string];
  }>(),
  { titles: () => ["待选", "已选"] },
);

const value = defineModel<string[]>({ default: () => [] });
const leftChecked = ref<string[]>([]);
const rightChecked = ref<string[]>([]);
const selected = computed(() => new Set(value.value));
const left = computed(() => props.data.filter((d) => !selected.value.has(d.key)));
const right = computed(() => props.data.filter((d) => selected.value.has(d.key)));

function toggle(list: string[], key: string, on: boolean) {
  return on ? [...list, key] : list.filter((k) => k !== key);
}

function moveRight() {
  value.value = [...value.value, ...leftChecked.value];
  leftChecked.value = [];
}

function moveLeft() {
  const drop = new Set(rightChecked.value);
  value.value = value.value.filter((k) => !drop.has(k));
  rightChecked.value = [];
}
</script>

<template>
  <div class="ag-transfer">
    <div class="ag-transfer__panel">
      <div class="ag-transfer__head">{{ titles[0] }}（{{ left.length }}）</div>
      <ul class="ag-transfer__list">
        <li v-for="it in left" :key="it.key">
          <Checkbox
            :model-value="leftChecked.includes(it.key)"
            :disabled="it.disabled"
            @update:model-value="leftChecked = toggle(leftChecked, it.key, $event)"
          >
            {{ it.label }}
          </Checkbox>
        </li>
      </ul>
    </div>
    <div class="ag-transfer__ops">
      <Button size="sm" :disabled="!leftChecked.length" aria-label="移到右侧" @click="moveRight">›</Button>
      <Button size="sm" variant="neutral" :disabled="!rightChecked.length" aria-label="移到左侧" @click="moveLeft">
        ‹
      </Button>
    </div>
    <div class="ag-transfer__panel">
      <div class="ag-transfer__head">{{ titles[1] }}（{{ right.length }}）</div>
      <ul class="ag-transfer__list">
        <li v-for="it in right" :key="it.key">
          <Checkbox
            :model-value="rightChecked.includes(it.key)"
            :disabled="it.disabled"
            @update:model-value="rightChecked = toggle(rightChecked, it.key, $event)"
          >
            {{ it.label }}
          </Checkbox>
        </li>
      </ul>
    </div>
  </div>
</template>
