// packages/calendar/src/svelte/ArgonCalendar.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import { Calendar } from "@fullcalendar/core";
  import dayGridPlugin from "@fullcalendar/daygrid";
  import interactionPlugin from "@fullcalendar/interaction";
  import {
    argonCalendarDefaults,
    toFullCalendarEvents,
    type ArgonCalendarProps,
  } from "../core/config";

  let {
    events = [],
    initialView,
    selectable = false,
    editable = false,
    options,
    ondateclick,
    oneventclick,
    oneventdrop,
  }: ArgonCalendarProps & {
    ondateclick?: ArgonCalendarProps["onDateClick"];
    oneventclick?: ArgonCalendarProps["onEventClick"];
    oneventdrop?: ArgonCalendarProps["onEventDrop"];
  } = $props();

  let el: HTMLDivElement;

  onMount(() => {
    if (!el) return;
    const calendar = new Calendar(el, {
      plugins: [dayGridPlugin, interactionPlugin],
      ...argonCalendarDefaults,
      initialView,
      selectable,
      editable,
      events: toFullCalendarEvents(events),
      dateClick: (info) => ondateclick?.({ dateStr: info.dateStr }),
      eventClick: (info) =>
        oneventclick?.({
          id: info.event.id || undefined,
          title: info.event.title,
          startStr: info.event.startStr,
        }),
      eventDrop: (info) =>
        oneventdrop?.({
          id: info.event.id || undefined,
          title: info.event.title,
          startStr: info.event.startStr,
        }),
      ...options,
    });
    calendar.render();
    return () => calendar.destroy();
  });
</script>

<div bind:this={el} class="ag-fc"></div>

// packages/calendar/src/vue/ArgonCalendar.vue
<script setup lang="ts">
import { onBeforeUnmount, onMounted, ref } from "vue";
import { Calendar } from "@fullcalendar/core";
import dayGridPlugin from "@fullcalendar/daygrid";
import interactionPlugin from "@fullcalendar/interaction";
import {
  argonCalendarDefaults,
  toFullCalendarEvents,
  type ArgonCalendarProps,
} from "../core/config";

const props = withDefaults(defineProps<ArgonCalendarProps>(), {
  events: () => [],
  selectable: false,
  editable: false,
});

const elRef = ref<HTMLElement | null>(null);
let calendar: Calendar | null = null;

onMounted(() => {
  if (!elRef.value) return;
  calendar = new Calendar(elRef.value, {
    plugins: [dayGridPlugin, interactionPlugin],
    ...argonCalendarDefaults,
    initialView: props.initialView,
    selectable: props.selectable,
    editable: props.editable,
    events: toFullCalendarEvents(props.events),
    dateClick: (info) => props.onDateClick?.({ dateStr: info.dateStr }),
    eventClick: (info) =>
      props.onEventClick?.({
        id: info.event.id || undefined,
        title: info.event.title,
        startStr: info.event.startStr,
      }),
    eventDrop: (info) =>
      props.onEventDrop?.({
        id: info.event.id || undefined,
        title: info.event.title,
        startStr: info.event.startStr,
      }),
    ...props.options,
  });
  calendar.render();
});

onBeforeUnmount(() => calendar?.destroy());
</script>

<template>
  <div ref="elRef" class="ag-fc" />
</template>
