// packages/vue/src/layout/Menu.vue
<script setup lang="ts">
import { glyphs, type GlyphName } from "@argon-kit/icons";
import type { ShellMenuItem } from "@argon-kit/core";
import Glyph from "../glyph/Glyph.vue";
import Menu from "./Menu.vue";

defineProps<{
  items: ShellMenuItem[];
  selectedKey?: string;
  openKeys: string[];
}>();

const emit = defineEmits<{
  select: [key: string];
  openChange: [keys: string[]];
}>();

function isGlyph(name?: string): name is GlyphName {
  return !!name && name in glyphs;
}
</script>

<template>
  <ul class="ag-menu">
    <li v-for="item in items" :key="item.key">
      <button
        type="button"
        :disabled="item.disabled"
        :class="['ag-menu__item', selectedKey === item.key ? 'is-active' : '']"
        @click="
          item.children?.length
            ? emit(
                'openChange',
                openKeys.includes(item.key) ? openKeys.filter((k) => k !== item.key) : [...openKeys, item.key],
              )
            : emit('select', item.key)
        "
      >
        <span class="ag-menu__icon">
          <Glyph v-if="isGlyph(item.icon)" :name="item.icon" />
          <span v-else class="ag-menu__dot" />
        </span>
        <span class="ag-menu__label">{{ item.label }}</span>
        <Glyph
          v-if="item.children?.length"
          name="chevronRight"
          :class="'ag-icon ag-menu__arrow' + (openKeys.includes(item.key) ? ' is-open' : '')"
        />
      </button>
      <Menu
        v-if="item.children?.length && openKeys.includes(item.key)"
        :items="item.children"
        :selected-key="selectedKey"
        :open-keys="openKeys"
        @select="emit('select', $event)"
        @open-change="emit('openChange', $event)"
      />
    </li>
  </ul>
</template>

// packages/svelte/src/layout/Menu.svelte
<script lang="ts">
  import { glyphs, type GlyphName } from "@argon-kit/icons";
  import type { ShellMenuItem } from "@argon-kit/core";
  import Glyph from "../glyph/Glyph.svelte";
  import Menu from "./Menu.svelte";

  let {
    items,
    selectedKey,
    openKeys,
    onselect,
    onopenchange,
  }: {
    items: ShellMenuItem[];
    selectedKey?: string;
    openKeys: string[];
    onselect?: (key: string) => void;
    onopenchange?: (keys: string[]) => void;
  } = $props();

  function isGlyph(name?: string): name is GlyphName {
    return !!name && name in glyphs;
  }

  function toggle(key: string) {
    onopenchange?.(openKeys.includes(key) ? openKeys.filter((k) => k !== key) : [...openKeys, key]);
  }
</script>

<ul class="ag-menu">
  {#each items as item (item.key)}
    <li>
      <button
        type="button"
        disabled={item.disabled}
        class={["ag-menu__item", selectedKey === item.key ? "is-active" : ""].filter(Boolean).join(" ")}
        onclick={() => (item.children?.length ? toggle(item.key) : onselect?.(item.key))}
      >
        <span class="ag-menu__icon">
          {#if isGlyph(item.icon)}
            <Glyph name={item.icon} />
          {:else}
            <span class="ag-menu__dot"></span>
          {/if}
        </span>
        <span class="ag-menu__label">{item.label}</span>
        {#if item.children?.length}
          <Glyph
            name="chevronRight"
            class={"ag-icon ag-menu__arrow" + (openKeys.includes(item.key) ? " is-open" : "")}
          />
        {/if}
      </button>
      {#if item.children?.length && openKeys.includes(item.key)}
        <Menu
          items={item.children}
          {selectedKey}
          {openKeys}
          {onselect}
          {onopenchange}
        />
      {/if}
    </li>
  {/each}
</ul>
