// packages/charts/src/svelte/Chart.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import { Chart, registerables, type ChartConfiguration, type ChartType } from "chart.js";
  import {
    applyChartDefaults,
    baseOptionsFor,
    withPalette,
    type ChartKind,
  } from "../core/chartTheme";

  Chart.register(...registerables);
  applyChartDefaults(Chart);

  let {
    kind = "line",
    labels,
    datasets,
    options = {},
    height = 300,
  }: {
    kind?: ChartKind;
    labels: string[];
    datasets: Array<Record<string, unknown>>;
    options?: Record<string, unknown>;
    height?: number;
  } = $props();

  let canvas: HTMLCanvasElement;
  let chart: Chart | null = null;
  let currentKind: ChartKind = kind;

  function buildConfig(): ChartConfiguration {
    return {
      type: kind as ChartType,
      data: {
        labels,
        datasets: withPalette(datasets as Array<{ backgroundColor?: unknown }>) as never,
      },
      options: { ...baseOptionsFor(kind), ...options },
    };
  }

  onMount(() => {
    currentKind = kind;
    chart = canvas ? new Chart(canvas, buildConfig()) : null;
    return () => chart?.destroy();
  });

  // kind 变化 → 重建
  $effect(() => {
    if (kind === currentKind) return;
    currentKind = kind;
    chart?.destroy();
    chart = canvas ? new Chart(canvas, buildConfig()) : null;
  });

  // 数据/options 变化 → 原地更新
  $effect(() => {
    void labels;
    void datasets;
    void options;
    if (!chart || kind !== currentKind) return;
    chart.data.labels = labels;
    chart.data.datasets = withPalette(datasets as Array<{ backgroundColor?: unknown }>) as never;
    chart.options = { ...baseOptionsFor(kind), ...options };
    chart.update();
  });
</script>

<div class="ag-chart" style="height:{height}px">
  <!-- svelte-ignore a11y_no_noninteractive_element_interactions -->
  <canvas bind:this={canvas}></canvas>
</div>

// packages/charts/src/vue/Chart.vue
<script setup lang="ts">
import { onBeforeUnmount, onMounted, ref, watch } from "vue";
import { Chart, registerables, type ChartConfiguration, type ChartType } from "chart.js";
import {
  applyChartDefaults,
  baseOptionsFor,
  withPalette,
  type ChartKind,
} from "../core/chartTheme";

Chart.register(...registerables);
applyChartDefaults(Chart);

const props = withDefaults(
  defineProps<{
    kind?: ChartKind;
    labels: string[];
    datasets: Array<Record<string, unknown>>;
    options?: Record<string, unknown>;
    height?: number;
  }>(),
  { kind: "line", height: 300 },
);

const canvasRef = ref<HTMLCanvasElement | null>(null);
let chart: Chart | null = null;

function buildConfig(): ChartConfiguration {
  return {
    type: props.kind as ChartType,
    data: {
      labels: props.labels,
      datasets: withPalette(
        props.datasets as Array<{ backgroundColor?: unknown }>,
      ) as never,
    },
    options: {
      ...baseOptionsFor(props.kind),
      ...props.options,
    },
  };
}

onMounted(() => {
  if (!canvasRef.value) return;
  chart = new Chart(canvasRef.value, buildConfig());
});

// kind 变化 → 重建（类型不同无法原地改）
watch(
  () => props.kind,
  () => {
    chart?.destroy();
    chart = canvasRef.value ? new Chart(canvasRef.value, buildConfig()) : null;
  },
);

// 数据/options 变化 → 原地更新（高频刷新场景不重建 canvas）
watch(
  () => [props.labels, props.datasets, props.options] as const,
  () => {
    if (!chart) return;
    chart.data.labels = props.labels;
    chart.data.datasets = withPalette(
      props.datasets as Array<{ backgroundColor?: unknown }>,
    ) as never;
    chart.options = { ...baseOptionsFor(props.kind), ...props.options };
    chart.update();
  },
  { deep: true },
);

onBeforeUnmount(() => chart?.destroy());
</script>

<template>
  <div class="ag-chart" :style="{ height: height + 'px' }">
    <canvas ref="canvasRef" />
  </div>
</template>
