// packages/svelte/src/layout/Menu.svelte
<script lang="ts">
  import { glyphs, type GlyphName } from "@argon-kit/icons";
  import type { ShellMenuItem } from "@argon-kit/core";
  import Glyph from "../glyph/Glyph.svelte";
  import Menu from "./Menu.svelte";

  let {
    items,
    selectedKey,
    openKeys,
    onselect,
    onopenchange,
  }: {
    items: ShellMenuItem[];
    selectedKey?: string;
    openKeys: string[];
    onselect?: (key: string) => void;
    onopenchange?: (keys: string[]) => void;
  } = $props();

  function isGlyph(name?: string): name is GlyphName {
    return !!name && name in glyphs;
  }

  function toggle(key: string) {
    onopenchange?.(openKeys.includes(key) ? openKeys.filter((k) => k !== key) : [...openKeys, key]);
  }
</script>

<ul class="ag-menu">
  {#each items as item (item.key)}
    <li>
      <button
        type="button"
        disabled={item.disabled}
        class={["ag-menu__item", selectedKey === item.key ? "is-active" : ""].filter(Boolean).join(" ")}
        onclick={() => (item.children?.length ? toggle(item.key) : onselect?.(item.key))}
      >
        <span class="ag-menu__icon">
          {#if isGlyph(item.icon)}
            <Glyph name={item.icon} />
          {:else}
            <span class="ag-menu__dot"></span>
          {/if}
        </span>
        <span class="ag-menu__label">{item.label}</span>
        {#if item.children?.length}
          <Glyph
            name="chevronRight"
            class={"ag-icon ag-menu__arrow" + (openKeys.includes(item.key) ? " is-open" : "")}
          />
        {/if}
      </button>
      {#if item.children?.length && openKeys.includes(item.key)}
        <Menu
          items={item.children}
          {selectedKey}
          {openKeys}
          {onselect}
          {onopenchange}
        />
      {/if}
    </li>
  {/each}
</ul>

// packages/react/src/layout/Menu.tsx
import { glyphs, type GlyphName } from "@argon-kit/icons";
import type { ShellMenuItem } from "@argon-kit/core";
import { Glyph } from "../glyph/Glyph";

function MenuIcon({ name }: { name?: string }) {
  if (name && name in glyphs) return <Glyph name={name as GlyphName} />;
  return <span className="ag-menu__dot" />;
}

export function Menu({
  items,
  selectedKey,
  openKeys,
  onSelect,
  onOpenChange,
}: {
  items: ShellMenuItem[];
  selectedKey?: string;
  openKeys: string[];
  onSelect?: (key: string) => void;
  onOpenChange?: (keys: string[]) => void;
}) {
  function toggle(key: string) {
    const next = openKeys.includes(key) ? openKeys.filter((k) => k !== key) : [...openKeys, key];
    onOpenChange?.(next);
  }

  function render(list: ShellMenuItem[]) {
    return (
      <ul className="ag-menu">
        {list.map((item) => {
          const hasKids = Boolean(item.children?.length);
          const open = openKeys.includes(item.key);
          return (
            <li key={item.key}>
              <button
                type="button"
                disabled={item.disabled}
                className={["ag-menu__item", selectedKey === item.key ? "is-active" : ""]
                  .filter(Boolean)
                  .join(" ")}
                onClick={() => (hasKids ? toggle(item.key) : onSelect?.(item.key))}
              >
                <span className="ag-menu__icon">
                  <MenuIcon name={item.icon} />
                </span>
                <span className="ag-menu__label">{item.label}</span>
                {hasKids ? (
                  <Glyph name="chevronRight" className={["ag-icon", "ag-menu__arrow", open ? "is-open" : ""].join(" ")} />
                ) : null}
              </button>
              {hasKids && open ? render(item.children!) : null}
            </li>
          );
        })}
      </ul>
    );
  }

  return render(items);
}
