// packages/vue/src/alert/Alert.vue
<script setup lang="ts">
import { computed, ref, useSlots } from "vue";

export type AlertVariant =
  | "default"
  | "primary"
  | "info"
  | "success"
  | "warning"
  | "danger";

const props = withDefaults(
  defineProps<{
    variant?: AlertVariant;
    dismissible?: boolean;
  }>(),
  { variant: "default", dismissible: false },
);

const emit = defineEmits<{ close: [] }>();

const visible = ref(true);
const slots = useSlots();

const className = computed(() =>
  props.variant === "default" ? "ag-alert" : `ag-alert ag-alert--${props.variant}`,
);
</script>

<template>
  <div v-if="visible" :class="className" role="alert">
    <span v-if="slots.icon || $slots.icon" class="ag-alert__icon"><slot name="icon" /></span>
    <div class="ag-alert__content"><slot /></div>
    <button
      v-if="dismissible"
      type="button"
      class="ag-alert__close"
      aria-label="close"
      @click="visible = false; emit('close')"
    >
      ×
    </button>
  </div>
</template>

// packages/react/src/alert/Alert.tsx
import { useState, type ReactNode } from "react";

export type AlertVariant =
  | "default"
  | "primary"
  | "info"
  | "success"
  | "warning"
  | "danger";

export interface AlertProps {
  variant?: AlertVariant;
  dismissible?: boolean;
  icon?: ReactNode;
  onClose?: () => void;
  children?: ReactNode;
}

export function Alert({
  variant = "default",
  dismissible = false,
  icon,
  onClose,
  children,
}: AlertProps) {
  const [visible, setVisible] = useState(true);
  if (!visible) return null;

  return (
    <div
      className={variant === "default" ? "ag-alert" : `ag-alert ag-alert--${variant}`}
      role="alert"
    >
      {icon ? <span className="ag-alert__icon">{icon}</span> : null}
      <div className="ag-alert__content">{children}</div>
      {dismissible ? (
        <button
          type="button"
          className="ag-alert__close"
          aria-label="close"
          onClick={() => {
            setVisible(false);
            onClose?.();
          }}
        >
          ×
        </button>
      ) : null}
    </div>
  );
}
