// packages/vue/src/collapse/Collapse.vue
<script setup lang="ts">
import { computed, provide } from "vue";

const props = withDefaults(
  defineProps<{
    modelValue?: string[];
    accordion?: boolean;
  }>(),
  { modelValue: () => [], accordion: false },
);

const emit = defineEmits<{ "update:modelValue": [string[]] }>();

const activeKeys = computed(() => props.modelValue);

function toggle(key: string) {
  const active = activeKeys.value;
  let next: string[];
  if (props.accordion) {
    next = active.includes(key) ? [] : [key];
  } else {
    next = active.includes(key) ? active.filter((k) => k !== key) : [...active, key];
  }
  emit("update:modelValue", next);
}

function isActive(key: string) {
  return activeKeys.value.includes(key);
}

provide("agCollapse", { toggle, isActive });
</script>

<template>
  <div class="ag-collapse">
    <slot />
  </div>
</template>

// packages/svelte/src/collapse/Collapse.svelte
<script lang="ts">
  import { getContext, setContext } from "svelte";
  import type { Snippet } from "svelte";

  let {
    value = $bindable([]),
    accordion = false,
    onChange,
    children,
  }: {
    value?: string[];
    accordion?: boolean;
    onChange?: (keys: string[]) => void;
    children?: Snippet;
  } = $props();

  function toggle(key: string) {
    if (accordion) {
      value = value.includes(key) ? [] : [key];
    } else {
      value = value.includes(key)
        ? value.filter((k) => k !== key)
        : [...value, key];
    }
    onChange?.(value);
  }

  function isActive(key: string) {
    return value.includes(key);
  }

  setContext("agCollapse", { toggle, isActive });
</script>

<div class="ag-collapse" data-accordion={accordion}>
  {@render children?.()}
</div>
