// packages/react/src/spin/Spin.tsx
import type { ReactNode } from "react";

export type SpinSize = "sm" | "md" | "lg";

export interface SpinProps {
  spinning?: boolean;
  size?: SpinSize;
  text?: string;
  children?: ReactNode;
}

export function Spin({ spinning = true, size = "md", text, children }: SpinProps) {
  const sizeClass = size !== "md" ? ` ag-spin--${size}` : "";

  if (children) {
    return (
      <div className={`ag-spin ag-spin--wrap${sizeClass}`}>
        {children}
        {spinning ? (
          <div className="ag-spin__mask">
            <span className="ag-spin__spinner" />
            {text ? <span className="ag-spin__text">{text}</span> : null}
          </div>
        ) : null}
      </div>
    );
  }

  return (
    <div className={`ag-spin${sizeClass}`}>
      <span className="ag-spin__spinner" />
      {text ? <span className="ag-spin__text">{text}</span> : null}
    </div>
  );
}

// packages/svelte/src/spin/Spin.svelte
<script lang="ts">
  import type { Snippet } from "svelte";

  let {
    spinning = true,
    size = "md",
    text = "",
    children,
  }: {
    spinning?: boolean;
    size?: "sm" | "md" | "lg";
    text?: string;
    children?: Snippet;
  } = $props();

  const sizeClass = $derived(size !== "md" ? ` ag-spin--${size}` : "");
</script>

{#if children}
  <div class={"ag-spin ag-spin--wrap" + sizeClass}>
    {@render children()}
    {#if spinning}
      <div class="ag-spin__mask">
        <span class="ag-spin__spinner"></span>
        {#if text}<span class="ag-spin__text">{text}</span>{/if}
      </div>
    {/if}
  </div>
{:else}
  <div class={"ag-spin" + sizeClass}>
    <span class="ag-spin__spinner"></span>
    {#if text}<span class="ag-spin__text">{text}</span>{/if}
  </div>
{/if}
