// packages/vue/src/upload/Upload.vue
<script setup lang="ts">
import { ref } from "vue";
import Button from "../button/Button.vue";

const files = defineModel<File[]>({ default: () => [] });
defineProps<{
  accept?: string;
  multiple?: boolean;
  disabled?: boolean;
  buttonText?: string;
}>();

const inputRef = ref<HTMLInputElement | null>(null);

function onPick(e: Event) {
  files.value = Array.from((e.target as HTMLInputElement).files ?? []);
}
</script>

<template>
  <div class="ag-upload">
    <input
      ref="inputRef"
      class="ag-upload__input"
      type="file"
      :accept="accept"
      :multiple="multiple"
      :disabled="disabled"
      @change="onPick"
    />
    <Button variant="neutral" :disabled="disabled" @click="inputRef?.click()">
      {{ buttonText ?? "选择文件" }}
    </Button>
    <ul v-if="files.length" class="ag-upload__list">
      <li v-for="f in files" :key="f.name + f.size" class="ag-upload__item">{{ f.name }}</li>
    </ul>
  </div>
</template>

// packages/react/src/upload/Upload.tsx
import { useRef } from "react";
import { Button } from "../button/Button";

export interface UploadProps {
  accept?: string;
  multiple?: boolean;
  disabled?: boolean;
  files?: File[];
  onChange?: (files: File[]) => void;
  buttonText?: string;
}

export function Upload({
  accept,
  multiple,
  disabled,
  files = [],
  onChange,
  buttonText = "选择文件",
}: UploadProps) {
  const inputRef = useRef<HTMLInputElement>(null);

  return (
    <div className="ag-upload">
      <input
        ref={inputRef}
        className="ag-upload__input"
        type="file"
        accept={accept}
        multiple={multiple}
        disabled={disabled}
        onChange={(e) => onChange?.(Array.from(e.target.files ?? []))}
      />
      <Button
        variant="neutral"
        disabled={disabled}
        onClick={() => inputRef.current?.click()}
      >
        {buttonText}
      </Button>
      {files.length > 0 ? (
        <ul className="ag-upload__list">
          {files.map((f) => (
            <li key={f.name + f.size} className="ag-upload__item">
              {f.name}
            </li>
          ))}
        </ul>
      ) : null}
    </div>
  );
}
