// packages/svelte/src/overlay/Popover.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import type { Snippet } from "svelte";

  let { children, content }: { children?: Snippet; content?: Snippet } = $props();
  let open = $state(false);
  let root: HTMLDivElement | undefined;

  onMount(() => {
    const onDoc = (e: MouseEvent) => {
      if (!root?.contains(e.target as Node)) open = false;
    };
    document.addEventListener("mousedown", onDoc);
    return () => document.removeEventListener("mousedown", onDoc);
  });
</script>

<div class="ag-overlay-root" bind:this={root}>
  <span onclick={() => (open = !open)}>{@render children?.()}</span>
  {#if open}
    <div class="ag-popover">{@render content?.()}</div>
  {/if}
</div>

// packages/vue/src/overlay/Popover.vue
<script setup lang="ts">
import { onMounted, onUnmounted, ref } from "vue";

const open = ref(false);
const root = ref<HTMLElement | null>(null);
const onDoc = (e: MouseEvent) => {
  if (!root.value?.contains(e.target as Node)) open.value = false;
};
onMounted(() => document.addEventListener("mousedown", onDoc));
onUnmounted(() => document.removeEventListener("mousedown", onDoc));
</script>

<template>
  <div ref="root" class="ag-overlay-root">
    <span @click="open = !open"><slot /></span>
    <div v-if="open" class="ag-popover"><slot name="content" /></div>
  </div>
</template>
