// packages/svelte/src/input/Password.svelte
<script lang="ts">
  import type { Snippet } from "svelte";
  import Input from "./Input.svelte";
  import Glyph from "../glyph/Glyph.svelte";
  import type { FieldStatus } from "./types";

  let {
    value = $bindable(""),
    placeholder,
    disabled = false,
    status,
    hint,
    prefix,
  }: {
    value?: string;
    placeholder?: string;
    disabled?: boolean;
    status?: FieldStatus;
    hint?: string;
    prefix?: Snippet;
  } = $props();

  let visible = $state(false);
</script>

<Input
  bind:value
  type={visible ? "text" : "password"}
  {placeholder}
  {disabled}
  {status}
  {hint}
  {prefix}
>
  {#snippet suffix()}
    <button
      type="button"
      class="ag-input__addon-btn"
      aria-label={visible ? "隐藏密码" : "显示密码"}
      onclick={() => (visible = !visible)}
    >
      <Glyph name={visible ? "eyeOff" : "eye"} />
    </button>
  {/snippet}
</Input>

// packages/vue/src/input/Password.vue
<script setup lang="ts">
import { ref } from "vue";
import Input from "./Input.vue";
import Glyph from "../glyph/Glyph.vue";
import type { FieldStatus } from "./types";

const model = defineModel<string>({ default: "" });
defineProps<{
  placeholder?: string;
  disabled?: boolean;
  status?: FieldStatus;
  hint?: string;
}>();
const visible = ref(false);
</script>

<template>
  <Input
    v-model="model"
    :type="visible ? 'text' : 'password'"
    :placeholder="placeholder"
    :disabled="disabled"
    :status="status"
    :hint="hint"
  >
    <template v-if="$slots.prefix" #prefix><slot name="prefix" /></template>
    <template #suffix>
      <button
        type="button"
        class="ag-input__addon-btn"
        :aria-label="visible ? '隐藏密码' : '显示密码'"
        @click="visible = !visible"
      >
        <Glyph :name="visible ? 'eyeOff' : 'eye'" />
      </button>
    </template>
  </Input>
</template>
