// packages/svelte/src/badge/Tag.svelte
<script lang="ts">
  import type { Snippet } from "svelte";

  let {
    variant = "default",
    dot = true,
    closable = false,
    children,
    onclose,
  }: {
    variant?: "default" | "primary" | "info" | "success" | "warning" | "danger";
    dot?: boolean;
    closable?: boolean;
    children?: Snippet;
    onclose?: (e: MouseEvent) => void;
  } = $props();

  const className = $derived(
    variant === "default" ? "ag-tag" : `ag-tag ag-tag--${variant}`,
  );
</script>

<span class={className}>
  {#if dot}<span class="ag-tag__dot"></span>{/if}
  {@render children?.()}
  {#if closable}
    <button
      type="button"
      class="ag-tag__close"
      aria-label="close"
      onclick={(e) => onclose?.(e)}
    >×</button>
  {/if}
</span>

// packages/vue/src/badge/Tag.vue
<script setup lang="ts">
import { computed } from "vue";

export type TagVariant =
  | "default"
  | "primary"
  | "info"
  | "success"
  | "warning"
  | "danger";

const props = withDefaults(
  defineProps<{
    variant?: TagVariant;
    dot?: boolean;
    closable?: boolean;
  }>(),
  { variant: "default", dot: true, closable: false },
);

const emit = defineEmits<{ close: [MouseEvent] }>();

const className = computed(() =>
  props.variant === "default" ? "ag-tag" : `ag-tag ag-tag--${props.variant}`,
);
</script>

<template>
  <span :class="className">
    <span v-if="dot" class="ag-tag__dot" />
    <slot />
    <button
      v-if="closable"
      type="button"
      class="ag-tag__close"
      aria-label="close"
      @click="emit('close', $event)"
    >
      ×
    </button>
  </span>
</template>
