// packages/vue/src/tree/TreeSelect.vue
<script setup lang="ts">
import { onMounted, onUnmounted, ref } from "vue";
import type { TreeNode } from "@argon-kit/core";
import Glyph from "../glyph/Glyph.vue";
import TreeNodes from "./TreeNodes.vue";

const model = defineModel<string | number | null>({ default: null });
const props = withDefaults(
  defineProps<{
    data: TreeNode[];
    placeholder?: string;
    allowClear?: boolean;
    status?: "error" | "success";
  }>(),
  { placeholder: "请选择", allowClear: false },
);

const emit = defineEmits<{
  change: [id: string | number | null, node: TreeNode | null];
}>();

const open = ref(false);
const expanded = ref(new Set<string>());
const root = ref<HTMLElement | null>(null);

function findLabel(nodes: TreeNode[], id: string | number | null): string {
  if (id == null) return "";
  for (const n of nodes) {
    if (n.id === id) return n.label;
    if (n.children) {
      const hit = findLabel(n.children, id);
      if (hit) return hit;
    }
  }
  return "";
}

function toggle(id: string | number) {
  const key = String(id);
  const next = new Set(expanded.value);
  if (next.has(key)) next.delete(key);
  else next.add(key);
  expanded.value = next;
}

function pick(node: TreeNode) {
  model.value = node.id;
  emit("change", node.id, node);
  open.value = false;
}

function clear() {
  model.value = null;
  emit("change", null, null);
}

const onDoc = (e: MouseEvent) => {
  if (!root.value?.contains(e.target as Node)) open.value = false;
};
onMounted(() => document.addEventListener("mousedown", onDoc));
onUnmounted(() => document.removeEventListener("mousedown", onDoc));
</script>

<template>
  <div ref="root" class="ag-field">
    <div class="ag-select">
      <div
        role="combobox"
        :aria-expanded="open"
        :class="['ag-input-wrap', 'ag-select__trigger', status ? `is-${status}` : '']"
        @click="open = !open"
      >
        <span :class="['ag-select__value', findLabel(data, model) ? '' : 'is-placeholder']">
          {{ findLabel(data, model) || placeholder }}
        </span>
        <button
          v-if="allowClear && model != null"
          type="button"
          class="ag-input__addon-btn"
          aria-label="清除"
          @click.stop="clear"
        >
          <Glyph name="x" />
        </button>
        <Glyph v-else name="chevronDown" />
      </div>
      <div v-if="open" class="ag-select__dropdown" style="padding: 8px; max-height: 280px; overflow: auto">
        <TreeNodes
          :nodes="data"
          :expanded="expanded"
          :selected="model"
          @toggle="toggle"
          @select="pick"
        />
      </div>
    </div>
  </div>
</template>

// packages/react/src/tree/TreeSelect.tsx
import { useEffect, useRef, useState } from "react";
import type { TreeNode } from "@argon-kit/core";
import { Glyph } from "../glyph/Glyph";

export type { TreeNode };

function findLabel(nodes: TreeNode[], id: string | number | null | undefined): string {
  if (id == null) return "";
  for (const n of nodes) {
    if (n.id === id) return n.label;
    if (n.children) {
      const hit = findLabel(n.children, id);
      if (hit) return hit;
    }
  }
  return "";
}

function TreeList({
  nodes,
  expanded,
  selected,
  onToggle,
  onSelect,
}: {
  nodes: TreeNode[];
  expanded: Set<string>;
  selected: string | number | null;
  onToggle: (id: string | number) => void;
  onSelect: (node: TreeNode) => void;
}) {
  return (
    <ul className="ag-tree">
      {nodes.map((n) => {
        const key = String(n.id);
        const hasKids = Boolean(n.children?.length);
        return (
          <li key={key}>
            <div
              className={[
                "ag-tree__node",
                n.id === selected ? "is-active" : "",
                n.disabled ? "is-disabled" : "",
              ]
                .filter(Boolean)
                .join(" ")}
              onClick={() => !n.disabled && onSelect(n)}
            >
              {hasKids ? (
                <button
                  type="button"
                  className={["ag-tree__twist", expanded.has(key) ? "is-open" : ""].filter(Boolean).join(" ")}
                  aria-label={expanded.has(key) ? "收起" : "展开"}
                  onClick={(e) => {
                    e.stopPropagation();
                    onToggle(n.id);
                  }}
                >
                  <Glyph name="chevronRight" />
                </button>
              ) : (
                <span className="ag-tree__leaf" />
              )}
              {n.label}
            </div>
            {hasKids && expanded.has(key) ? (
              <TreeList
                nodes={n.children!}
                expanded={expanded}
                selected={selected}
                onToggle={onToggle}
                onSelect={onSelect}
              />
            ) : null}
          </li>
        );
      })}
    </ul>
  );
}

export interface TreeSelectProps {
  data: TreeNode[];
  value?: string | number | null;
  onChange?: (id: string | number | null, node?: TreeNode | null) => void;
  placeholder?: string;
  allowClear?: boolean;
  status?: "error" | "success";
}

export function TreeSelect({
  data,
  value = null,
  onChange,
  placeholder = "请选择",
  allowClear,
  status,
}: TreeSelectProps) {
  const [open, setOpen] = useState(false);
  const [expanded, setExpanded] = useState<Set<string>>(new Set());
  const rootRef = useRef<HTMLDivElement>(null);
  const label = findLabel(data, value);

  useEffect(() => {
    const onDoc = (e: MouseEvent) => {
      if (!rootRef.current?.contains(e.target as Node)) setOpen(false);
    };
    document.addEventListener("mousedown", onDoc);
    return () => document.removeEventListener("mousedown", onDoc);
  }, []);

  return (
    <div className="ag-field" ref={rootRef}>
      <div className="ag-select">
        <div
          role="combobox"
          aria-expanded={open}
          className={["ag-input-wrap", "ag-select__trigger", status ? `is-${status}` : ""]
            .filter(Boolean)
            .join(" ")}
          onClick={() => setOpen((v) => !v)}
        >
          <span className={["ag-select__value", label ? "" : "is-placeholder"].filter(Boolean).join(" ")}>
            {label || placeholder}
          </span>
          {allowClear && value != null ? (
            <button
              type="button"
              className="ag-input__addon-btn"
              aria-label="清除"
              onClick={(e) => {
                e.stopPropagation();
                onChange?.(null, null);
              }}
            >
              <Glyph name="x" />
            </button>
          ) : (
            <Glyph name="chevronDown" />
          )}
        </div>
        {open ? (
          <div className="ag-select__dropdown" style={{ padding: 8, maxHeight: 280, overflow: "auto" }}>
            <TreeList
              nodes={data}
              expanded={expanded}
              selected={value}
              onToggle={(id) => {
                const key = String(id);
                setExpanded((prev) => {
                  const next = new Set(prev);
                  if (next.has(key)) next.delete(key);
                  else next.add(key);
                  return next;
                });
              }}
              onSelect={(node) => {
                onChange?.(node.id, node);
                setOpen(false);
              }}
            />
          </div>
        ) : null}
      </div>
    </div>
  );
}
